


from PyQt5 import QtCore, QtGui, QtWidgets
from supabase import create_client


class Ui_be_tt_display(object):
    def setupUi(self, be_tt_display):
        be_tt_display.setObjectName("be_tt_display")
        be_tt_display.showFullScreen()
        self.centralwidget = QtWidgets.QWidget(be_tt_display)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(290, 170, 1361, 701))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.m1 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.m1.setFont(font)
        self.m1.setText("")
        self.m1.setAlignment(QtCore.Qt.AlignCenter)
        self.m1.setObjectName("m1")
        self.gridLayout.addWidget(self.m1, 1, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 0, 5, 1, 1)
        self.label_34 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_34.setFont(font)
        self.label_34.setAlignment(QtCore.Qt.AlignCenter)
        self.label_34.setObjectName("label_34")
        self.gridLayout.addWidget(self.label_34, 0, 3, 1, 1)
        self.w2 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.w2.setFont(font)
        self.w2.setText("")
        self.w2.setAlignment(QtCore.Qt.AlignCenter)
        self.w2.setObjectName("w2")
        self.gridLayout.addWidget(self.w2, 2, 3, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 2, 0, 1, 1)
        self.m3 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.m3.setFont(font)
        self.m3.setText("")
        self.m3.setAlignment(QtCore.Qt.AlignCenter)
        self.m3.setObjectName("m3")
        self.gridLayout.addWidget(self.m3, 3, 1, 1, 1)
        self.w6 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.w6.setFont(font)
        self.w6.setText("")
        self.w6.setAlignment(QtCore.Qt.AlignCenter)
        self.w6.setObjectName("w6")
        self.gridLayout.addWidget(self.w6, 6, 3, 1, 1)
        self.th5 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.th5.setFont(font)
        self.th5.setText("")
        self.th5.setAlignment(QtCore.Qt.AlignCenter)
        self.th5.setObjectName("th5")
        self.gridLayout.addWidget(self.th5, 5, 4, 1, 1)
        self.tu6 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.tu6.setFont(font)
        self.tu6.setText("")
        self.tu6.setAlignment(QtCore.Qt.AlignCenter)
        self.tu6.setObjectName("tu6")
        self.gridLayout.addWidget(self.tu6, 6, 2, 1, 1)
        self.m7 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.m7.setText("")
        self.m7.setAlignment(QtCore.Qt.AlignCenter)
        self.m7.setObjectName("m7")
        self.gridLayout.addWidget(self.m7, 7, 1, 1, 1)
        self.f7 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.f7.setText("")
        self.f7.setAlignment(QtCore.Qt.AlignCenter)
        self.f7.setObjectName("f7")
        self.gridLayout.addWidget(self.f7, 7, 5, 1, 1)
        self.w1 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.w1.setFont(font)
        self.w1.setText("")
        self.w1.setAlignment(QtCore.Qt.AlignCenter)
        self.w1.setObjectName("w1")
        self.gridLayout.addWidget(self.w1, 1, 3, 1, 1)
        self.th2 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.th2.setFont(font)
        self.th2.setText("")
        self.th2.setAlignment(QtCore.Qt.AlignCenter)
        self.th2.setObjectName("th2")
        self.gridLayout.addWidget(self.th2, 2, 4, 1, 1)
        self.tu7 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.tu7.setText("")
        self.tu7.setAlignment(QtCore.Qt.AlignCenter)
        self.tu7.setObjectName("tu7")
        self.gridLayout.addWidget(self.tu7, 7, 2, 1, 1)
        self.th7 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.th7.setText("")
        self.th7.setAlignment(QtCore.Qt.AlignCenter)
        self.th7.setObjectName("th7")
        self.gridLayout.addWidget(self.th7, 7, 4, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 5, 0, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.gridLayout.addWidget(self.label_16, 6, 0, 1, 1)
        self.tu1 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.tu1.setFont(font)
        self.tu1.setText("")
        self.tu1.setAlignment(QtCore.Qt.AlignCenter)
        self.tu1.setObjectName("tu1")
        self.gridLayout.addWidget(self.tu1, 1, 2, 1, 1)
        self.th1 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.th1.setFont(font)
        self.th1.setText("")
        self.th1.setAlignment(QtCore.Qt.AlignCenter)
        self.th1.setObjectName("th1")
        self.gridLayout.addWidget(self.th1, 1, 4, 1, 1)
        self.f5 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.f5.setFont(font)
        self.f5.setText("")
        self.f5.setAlignment(QtCore.Qt.AlignCenter)
        self.f5.setObjectName("f5")
        self.gridLayout.addWidget(self.f5, 5, 5, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.gridLayout.addWidget(self.label_19, 0, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 3, 0, 1, 1)
        self.tu2 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.tu2.setFont(font)
        self.tu2.setText("")
        self.tu2.setAlignment(QtCore.Qt.AlignCenter)
        self.tu2.setObjectName("tu2")
        self.gridLayout.addWidget(self.tu2, 2, 2, 1, 1)
        self.m6 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.m6.setFont(font)
        self.m6.setText("")
        self.m6.setAlignment(QtCore.Qt.AlignCenter)
        self.m6.setObjectName("m6")
        self.gridLayout.addWidget(self.m6, 6, 1, 1, 1)
        self.th3 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.th3.setFont(font)
        self.th3.setText("")
        self.th3.setAlignment(QtCore.Qt.AlignCenter)
        self.th3.setObjectName("th3")
        self.gridLayout.addWidget(self.th3, 3, 4, 1, 1)
        self.tu5 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.tu5.setFont(font)
        self.tu5.setText("")
        self.tu5.setAlignment(QtCore.Qt.AlignCenter)
        self.tu5.setObjectName("tu5")
        self.gridLayout.addWidget(self.tu5, 5, 2, 1, 1)
        self.f6 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.f6.setFont(font)
        self.f6.setText("")
        self.f6.setAlignment(QtCore.Qt.AlignCenter)
        self.f6.setObjectName("f6")
        self.gridLayout.addWidget(self.f6, 6, 5, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.gridLayout.addWidget(self.label_20, 0, 1, 1, 1)
        self.f1 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.f1.setFont(font)
        self.f1.setText("")
        self.f1.setAlignment(QtCore.Qt.AlignCenter)
        self.f1.setObjectName("f1")
        self.gridLayout.addWidget(self.f1, 1, 5, 1, 1)
        self.m5 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.m5.setFont(font)
        self.m5.setText("")
        self.m5.setAlignment(QtCore.Qt.AlignCenter)
        self.m5.setObjectName("m5")
        self.gridLayout.addWidget(self.m5, 5, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 4, 1, 1)
        self.m2 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.m2.setFont(font)
        self.m2.setText("")
        self.m2.setAlignment(QtCore.Qt.AlignCenter)
        self.m2.setObjectName("m2")
        self.gridLayout.addWidget(self.m2, 2, 1, 1, 1)
        self.w5 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.w5.setFont(font)
        self.w5.setText("")
        self.w5.setAlignment(QtCore.Qt.AlignCenter)
        self.w5.setObjectName("w5")
        self.gridLayout.addWidget(self.w5, 5, 3, 1, 1)
        self.f2 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.f2.setFont(font)
        self.f2.setText("")
        self.f2.setAlignment(QtCore.Qt.AlignCenter)
        self.f2.setObjectName("f2")
        self.gridLayout.addWidget(self.f2, 2, 5, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.gridLayout.addWidget(self.label_18, 1, 0, 1, 1)
        self.w7 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.w7.setText("")
        self.w7.setAlignment(QtCore.Qt.AlignCenter)
        self.w7.setObjectName("w7")
        self.gridLayout.addWidget(self.w7, 7, 3, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.gridLayout.addWidget(self.label_17, 7, 0, 1, 1)
        self.f3 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.f3.setFont(font)
        self.f3.setText("")
        self.f3.setAlignment(QtCore.Qt.AlignCenter)
        self.f3.setObjectName("f3")
        self.gridLayout.addWidget(self.f3, 3, 5, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_33.setFont(font)
        self.label_33.setAlignment(QtCore.Qt.AlignCenter)
        self.label_33.setObjectName("label_33")
        self.gridLayout.addWidget(self.label_33, 0, 2, 1, 1)
        self.th6 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.th6.setFont(font)
        self.th6.setText("")
        self.th6.setAlignment(QtCore.Qt.AlignCenter)
        self.th6.setObjectName("th6")
        self.gridLayout.addWidget(self.th6, 6, 4, 1, 1)
        self.tu3 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.tu3.setFont(font)
        self.tu3.setText("")
        self.tu3.setAlignment(QtCore.Qt.AlignCenter)
        self.tu3.setObjectName("tu3")
        self.gridLayout.addWidget(self.tu3, 3, 2, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 4, 0, 1, 1)
        self.w3 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.w3.setFont(font)
        self.w3.setText("")
        self.w3.setAlignment(QtCore.Qt.AlignCenter)
        self.w3.setObjectName("w3")
        self.gridLayout.addWidget(self.w3, 3, 3, 1, 1)
        self.frame = QtWidgets.QFrame(self.gridLayoutWidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.m41 = QtWidgets.QLabel(self.frame)
        self.m41.setGeometry(QtCore.QRect(0, 0, 221, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.m41.setFont(font)
        self.m41.setText("")
        self.m41.setAlignment(QtCore.Qt.AlignCenter)
        self.m41.setObjectName("m41")
        self.m42 = QtWidgets.QLabel(self.frame)
        self.m42.setGeometry(QtCore.QRect(0, 30, 221, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.m42.setFont(font)
        self.m42.setText("")
        self.m42.setAlignment(QtCore.Qt.AlignCenter)
        self.m42.setObjectName("m42")
        self.m43 = QtWidgets.QLabel(self.frame)
        self.m43.setGeometry(QtCore.QRect(0, 60, 221, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.m43.setFont(font)
        self.m43.setText("")
        self.m43.setAlignment(QtCore.Qt.AlignCenter)
        self.m43.setObjectName("m43")
        self.gridLayout.addWidget(self.frame, 4, 1, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.tu41 = QtWidgets.QLabel(self.frame_2)
        self.tu41.setGeometry(QtCore.QRect(0, 0, 221, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.tu41.setFont(font)
        self.tu41.setText("")
        self.tu41.setAlignment(QtCore.Qt.AlignCenter)
        self.tu41.setObjectName("tu41")
        self.tu43 = QtWidgets.QLabel(self.frame_2)
        self.tu43.setGeometry(QtCore.QRect(0, 60, 221, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.tu43.setFont(font)
        self.tu43.setText("")
        self.tu43.setAlignment(QtCore.Qt.AlignCenter)
        self.tu43.setObjectName("tu43")
        self.tu42 = QtWidgets.QLabel(self.frame_2)
        self.tu42.setGeometry(QtCore.QRect(0, 30, 221, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.tu42.setFont(font)
        self.tu42.setText("")
        self.tu42.setAlignment(QtCore.Qt.AlignCenter)
        self.tu42.setObjectName("tu42")
        self.gridLayout.addWidget(self.frame_2, 4, 2, 1, 1)
        self.frame_3 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.w41 = QtWidgets.QLabel(self.frame_3)
        self.w41.setGeometry(QtCore.QRect(0, 0, 221, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.w41.setFont(font)
        self.w41.setText("")
        self.w41.setAlignment(QtCore.Qt.AlignCenter)
        self.w41.setObjectName("w41")
        self.w43 = QtWidgets.QLabel(self.frame_3)
        self.w43.setGeometry(QtCore.QRect(0, 60, 221, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.w43.setFont(font)
        self.w43.setText("")
        self.w43.setAlignment(QtCore.Qt.AlignCenter)
        self.w43.setObjectName("w43")
        self.w42 = QtWidgets.QLabel(self.frame_3)
        self.w42.setGeometry(QtCore.QRect(0, 30, 221, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.w42.setFont(font)
        self.w42.setText("")
        self.w42.setAlignment(QtCore.Qt.AlignCenter)
        self.w42.setObjectName("w42")
        self.gridLayout.addWidget(self.frame_3, 4, 3, 1, 1)
        self.frame_4 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.th41 = QtWidgets.QLabel(self.frame_4)
        self.th41.setGeometry(QtCore.QRect(0, 0, 221, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.th41.setFont(font)
        self.th41.setText("")
        self.th41.setAlignment(QtCore.Qt.AlignCenter)
        self.th41.setObjectName("th41")
        self.th43 = QtWidgets.QLabel(self.frame_4)
        self.th43.setGeometry(QtCore.QRect(0, 60, 221, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.th43.setFont(font)
        self.th43.setText("")
        self.th43.setAlignment(QtCore.Qt.AlignCenter)
        self.th43.setObjectName("th43")
        self.th42 = QtWidgets.QLabel(self.frame_4)
        self.th42.setGeometry(QtCore.QRect(0, 30, 221, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.th42.setFont(font)
        self.th42.setText("")
        self.th42.setAlignment(QtCore.Qt.AlignCenter)
        self.th42.setObjectName("th42")
        self.gridLayout.addWidget(self.frame_4, 4, 4, 1, 1)
        self.frame_5 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.f41 = QtWidgets.QLabel(self.frame_5)
        self.f41.setGeometry(QtCore.QRect(0, 0, 221, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.f41.setFont(font)
        self.f41.setText("")
        self.f41.setAlignment(QtCore.Qt.AlignCenter)
        self.f41.setObjectName("f41")
        self.f43 = QtWidgets.QLabel(self.frame_5)
        self.f43.setGeometry(QtCore.QRect(0, 60, 221, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.f43.setFont(font)
        self.f43.setText("")
        self.f43.setAlignment(QtCore.Qt.AlignCenter)
        self.f43.setObjectName("f43")
        self.f42 = QtWidgets.QLabel(self.frame_5)
        self.f42.setGeometry(QtCore.QRect(0, 30, 221, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.f42.setFont(font)
        self.f42.setText("")
        self.f42.setAlignment(QtCore.Qt.AlignCenter)
        self.f42.setObjectName("f42")
        self.gridLayout.addWidget(self.frame_5, 4, 5, 1, 1)
        self.label_49 = QtWidgets.QLabel(self.centralwidget)
        self.label_49.setGeometry(QtCore.QRect(650, 40, 671, 71))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(35)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_49.setFont(font)
        self.label_49.setAlignment(QtCore.Qt.AlignCenter)
        self.label_49.setObjectName("label_49")
        be_tt_display.setCentralWidget(self.centralwidget)
        self.get_and_update_timeTable()


        self.retranslateUi(be_tt_display)
        QtCore.QMetaObject.connectSlotsByName(be_tt_display)

    def retranslateUi(self, be_tt_display):
        _translate = QtCore.QCoreApplication.translate
        be_tt_display.setWindowTitle(_translate("be_tt_display", "MainWindow"))
        self.label_8.setText(_translate("be_tt_display", "Friday"))
        self.label_34.setText(_translate("be_tt_display", "Wednesday"))
        self.label_12.setText(_translate("be_tt_display", "10:15 PM - 11:15 AM"))
        self.label_15.setText(_translate("be_tt_display", "01:30 PM - 02:15 PM"))
        self.label_16.setText(_translate("be_tt_display", "02:15 PM - 03:15 PM"))
        self.label_19.setText(_translate("be_tt_display", "Time / Day"))
        self.label_13.setText(_translate("be_tt_display", "11:15 AM - 11:30 AM"))
        self.label_20.setText(_translate("be_tt_display", "Monday"))
        self.label_2.setText(_translate("be_tt_display", "Thursday"))
        self.label_18.setText(_translate("be_tt_display", "09:15 AM - 10:15 AM"))
        self.label_17.setText(_translate("be_tt_display", "03:15 PM - 04:15 PM"))
        self.label_33.setText(_translate("be_tt_display", "Tuesday"))
        self.label_14.setText(_translate("be_tt_display", "11:30 AM - 01:30 PM"))
        self.label_49.setText(_translate("be_tt_display", "BE E&TC Timetable"))

    def get_and_update_timeTable(self):
        url = "https://ctbocdqgvhimayeqvqov.supabase.co"
        key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN0Ym9jZHFndmhpbWF5ZXF2cW92Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MDYzNjQ1MzEsImV4cCI6MjAyMTk0MDUzMX0.HHOqs4_KujahCS_V60CsKWjb0ky4UTO2qQNzdyV0sdU"
        supabase = create_client(url, key)
        _translate = QtCore.QCoreApplication.translate
        response_1 = supabase.table("be_tt").select("*").eq("id", 1).execute()
        for data_1 in response_1.data:
            self.m1.setText(_translate("MainWindow", data_1["monday"]))
            self.tu1.setText(_translate("MainWindow", data_1["tuesday"]))
            self.w1.setText(_translate("MainWindow", data_1["wednesday"]))
            self.th1.setText(_translate("MainWindow", data_1["thursday"]))
            self.f1.setText(_translate("MainWindow", data_1["friday"]))
        response_2 = supabase.table("be_tt").select("*").eq("id", 2).execute()
        for data_2 in response_2.data:
            self.m2.setText(_translate("MainWindow", data_2["monday"]))
            self.tu2.setText(_translate("MainWindow", data_2["tuesday"]))
            self.w2.setText(_translate("MainWindow", data_2["wednesday"]))
            self.th2.setText(_translate("MainWindow", data_2["thursday"]))
            self.f2.setText(_translate("MainWindow", data_2["friday"]))
        response_3 = supabase.table("be_tt").select("*").eq("id", 3).execute()
        for data_3 in response_3.data:
            self.m3.setText(_translate("MainWindow", data_3["monday"]))
            self.tu3.setText(_translate("MainWindow", data_3["tuesday"]))
            self.w3.setText(_translate("MainWindow", data_3["wednesday"]))
            self.th3.setText(_translate("MainWindow", data_3["thursday"]))
            self.f3.setText(_translate("MainWindow", data_3["friday"]))
        response_4 = supabase.table("be_tt").select("*").eq("id", 4).execute()
        for data_4 in response_4.data:
            self.m41.setText(_translate("MainWindow", data_4["monday"]))
            self.tu41.setText(_translate("MainWindow", data_4["tuesday"]))
            self.w41.setText(_translate("MainWindow", data_4["wednesday"]))
            self.th41.setText(_translate("MainWindow", data_4["thursday"]))
            self.f41.setText(_translate("MainWindow", data_4["friday"]))
        response_5 = supabase.table("be_tt").select("*").eq("id", 5).execute()
        for data_5 in response_5.data:
            self.m42.setText(_translate("MainWindow", data_5["monday"]))
            self.tu42.setText(_translate("MainWindow", data_5["tuesday"]))
            self.w42.setText(_translate("MainWindow", data_5["wednesday"]))
            self.th42.setText(_translate("MainWindow", data_5["thursday"]))
            self.f42.setText(_translate("MainWindow", data_5["friday"]))
        response_6 = supabase.table("be_tt").select("*").eq("id", 6).execute()
        for data_6 in response_6.data:
            self.m43.setText(_translate("MainWindow", data_6["monday"]))
            self.tu43.setText(_translate("MainWindow", data_6["tuesday"]))
            self.w43.setText(_translate("MainWindow", data_6["wednesday"]))
            self.th43.setText(_translate("MainWindow", data_6["thursday"]))
            self.f43.setText(_translate("MainWindow", data_6["friday"]))
        response_7 = supabase.table("be_tt").select("*").eq("id", 7).execute()
        for data_7 in response_7.data:
            self.m5.setText(_translate("MainWindow", data_7["monday"]))
            self.tu5.setText(_translate("MainWindow", data_7["tuesday"]))
            self.w5.setText(_translate("MainWindow", data_7["wednesday"]))
            self.th5.setText(_translate("MainWindow", data_7["thursday"]))
            self.f5.setText(_translate("MainWindow", data_7["friday"]))
        response_8 = supabase.table("be_tt").select("*").eq("id", 8).execute()
        for data_8 in response_8.data:
            self.m6.setText(_translate("MainWindow", data_8["monday"]))
            self.tu6.setText(_translate("MainWindow", data_8["tuesday"]))
            self.w6.setText(_translate("MainWindow", data_8["wednesday"]))
            self.th6.setText(_translate("MainWindow", data_8["thursday"]))
            self.f6.setText(_translate("MainWindow", data_8["friday"]))
        response_9 = supabase.table("be_tt").select("*").eq("id", 9).execute()
        for data_9 in response_9.data:
            self.m7.setText(_translate("MainWindow", data_9["monday"]))
            self.tu7.setText(_translate("MainWindow", data_9["tuesday"]))
            self.w7.setText(_translate("MainWindow", data_9["wednesday"]))
            self.th7.setText(_translate("MainWindow", data_9["thursday"]))
            self.f7.setText(_translate("MainWindow", data_9["friday"]))



# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     be_tt_display = QtWidgets.QMainWindow()
#     ui = Ui_be_tt_display()
#     ui.setupUi(be_tt_display)
#     be_tt_display.show()
#     sys.exit(app.exec_())
