


from PyQt5 import QtCore, QtGui, QtWidgets
from supabase import create_client


class Ui_timetable_generator(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1279, 952)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(330, 80, 581, 71))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(25)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(70, 190, 1121, 601))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.gridLayoutWidget.setFont(font)
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.frame_27 = QtWidgets.QFrame(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.frame_27.setFont(font)
        self.frame_27.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_27.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_27.setObjectName("frame_27")
        self.th6 = QtWidgets.QComboBox(self.frame_27)
        self.th6.setGeometry(QtCore.QRect(28, 8, 126, 49))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.th6.setFont(font)
        self.th6.setObjectName("th6")
        self.gridLayout.addWidget(self.frame_27, 7, 4, 1, 1)
        self.frame_33 = QtWidgets.QFrame(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.frame_33.setFont(font)
        self.frame_33.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_33.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_33.setObjectName("frame_33")
        self.f5 = QtWidgets.QComboBox(self.frame_33)
        self.f5.setGeometry(QtCore.QRect(28, 13, 126, 49))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.f5.setFont(font)
        self.f5.setObjectName("f5")
        self.gridLayout.addWidget(self.frame_33, 6, 5, 1, 1)
        self.frame_32 = QtWidgets.QFrame(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.frame_32.setFont(font)
        self.frame_32.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_32.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_32.setObjectName("frame_32")
        self.f3 = QtWidgets.QComboBox(self.frame_32)
        self.f3.setGeometry(QtCore.QRect(28, 9, 126, 49))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.f3.setFont(font)
        self.f3.setObjectName("f3")
        self.gridLayout.addWidget(self.frame_32, 3, 5, 1, 1)
        self.frame_30 = QtWidgets.QFrame(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.frame_30.setFont(font)
        self.frame_30.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_30.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_30.setObjectName("frame_30")
        self.f2 = QtWidgets.QComboBox(self.frame_30)
        self.f2.setGeometry(QtCore.QRect(28, 9, 126, 49))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.f2.setFont(font)
        self.f2.setObjectName("f2")
        self.gridLayout.addWidget(self.frame_30, 2, 5, 1, 1)
        self.frame_21 = QtWidgets.QFrame(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.frame_21.setFont(font)
        self.frame_21.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_21.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_21.setObjectName("frame_21")
        self.w7 = QtWidgets.QComboBox(self.frame_21)
        self.w7.setGeometry(QtCore.QRect(28, 8, 126, 49))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.w7.setFont(font)
        self.w7.setObjectName("w7")
        self.gridLayout.addWidget(self.frame_21, 8, 3, 1, 1)
        self.frame_12 = QtWidgets.QFrame(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.frame_12.setFont(font)
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.tu5 = QtWidgets.QComboBox(self.frame_12)
        self.tu5.setGeometry(QtCore.QRect(28, 13, 126, 49))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.tu5.setFont(font)
        self.tu5.setObjectName("tu5")
        self.gridLayout.addWidget(self.frame_12, 6, 2, 1, 1)
        self.frame_4 = QtWidgets.QFrame(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.frame_4.setFont(font)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.m3 = QtWidgets.QComboBox(self.frame_4)
        self.m3.setGeometry(QtCore.QRect(28, 9, 126, 49))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.m3.setFont(font)
        self.m3.setObjectName("m3")
        self.gridLayout.addWidget(self.frame_4, 3, 1, 1, 1)
        self.frame_20 = QtWidgets.QFrame(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.frame_20.setFont(font)
        self.frame_20.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_20.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_20.setObjectName("frame_20")
        self.w6 = QtWidgets.QComboBox(self.frame_20)
        self.w6.setGeometry(QtCore.QRect(28, 8, 126, 49))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.w6.setFont(font)
        self.w6.setObjectName("w6")
        self.gridLayout.addWidget(self.frame_20, 7, 3, 1, 1)
        self.frame_10 = QtWidgets.QFrame(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.frame_10.setFont(font)
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.tu42 = QtWidgets.QComboBox(self.frame_10)
        self.tu42.setGeometry(QtCore.QRect(28, 26, 126, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.tu42.setFont(font)
        self.tu42.setObjectName("tu42")
        self.tu41 = QtWidgets.QComboBox(self.frame_10)
        self.tu41.setGeometry(QtCore.QRect(28, 0, 126, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.tu41.setFont(font)
        self.tu41.setObjectName("tu41")
        self.tu43 = QtWidgets.QComboBox(self.frame_10)
        self.tu43.setGeometry(QtCore.QRect(28, 50, 126, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.tu43.setFont(font)
        self.tu43.setObjectName("tu43")
        self.gridLayout.addWidget(self.frame_10, 4, 2, 1, 1)
        self.frame_7 = QtWidgets.QFrame(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.frame_7.setFont(font)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.m7 = QtWidgets.QComboBox(self.frame_7)
        self.m7.setGeometry(QtCore.QRect(28, 8, 126, 49))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.m7.setFont(font)
        self.m7.setObjectName("m7")
        self.gridLayout.addWidget(self.frame_7, 8, 1, 1, 1)
        self.frame_3 = QtWidgets.QFrame(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.frame_3.setFont(font)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.m41 = QtWidgets.QComboBox(self.frame_3)
        self.m41.setGeometry(QtCore.QRect(28, 0, 126, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.m41.setFont(font)
        self.m41.setObjectName("m41")
        self.m42 = QtWidgets.QComboBox(self.frame_3)
        self.m42.setGeometry(QtCore.QRect(28, 26, 126, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.m42.setFont(font)
        self.m42.setObjectName("m42")
        self.m43 = QtWidgets.QComboBox(self.frame_3)
        self.m43.setGeometry(QtCore.QRect(28, 50, 126, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.m43.setFont(font)
        self.m43.setObjectName("m43")
        self.gridLayout.addWidget(self.frame_3, 4, 1, 1, 1)
        self.frame_9 = QtWidgets.QFrame(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.frame_9.setFont(font)
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.tu2 = QtWidgets.QComboBox(self.frame_9)
        self.tu2.setGeometry(QtCore.QRect(28, 9, 126, 49))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.tu2.setFont(font)
        self.tu2.setObjectName("tu2")
        self.gridLayout.addWidget(self.frame_9, 2, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 3, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 1, 0, 1, 1)
        self.frame_28 = QtWidgets.QFrame(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.frame_28.setFont(font)
        self.frame_28.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_28.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_28.setObjectName("frame_28")
        self.th7 = QtWidgets.QComboBox(self.frame_28)
        self.th7.setGeometry(QtCore.QRect(28, 8, 126, 49))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.th7.setFont(font)
        self.th7.setObjectName("th7")
        self.gridLayout.addWidget(self.frame_28, 8, 4, 1, 1)
        self.frame_23 = QtWidgets.QFrame(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.frame_23.setFont(font)
        self.frame_23.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_23.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_23.setObjectName("frame_23")
        self.th2 = QtWidgets.QComboBox(self.frame_23)
        self.th2.setGeometry(QtCore.QRect(28, 9, 126, 49))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.th2.setFont(font)
        self.th2.setObjectName("th2")
        self.gridLayout.addWidget(self.frame_23, 2, 4, 1, 1)
        self.frame = QtWidgets.QFrame(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.frame.setFont(font)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.m1 = QtWidgets.QComboBox(self.frame)
        self.m1.setGeometry(QtCore.QRect(28, 9, 126, 49))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.m1.setFont(font)
        self.m1.setObjectName("m1")
        self.gridLayout.addWidget(self.frame, 1, 1, 1, 1)
        self.frame_35 = QtWidgets.QFrame(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.frame_35.setFont(font)
        self.frame_35.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_35.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_35.setObjectName("frame_35")
        self.f7 = QtWidgets.QComboBox(self.frame_35)
        self.f7.setGeometry(QtCore.QRect(28, 8, 126, 49))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.f7.setFont(font)
        self.f7.setObjectName("f7")
        self.gridLayout.addWidget(self.frame_35, 8, 5, 1, 1)
        self.frame_15 = QtWidgets.QFrame(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.frame_15.setFont(font)
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.w1 = QtWidgets.QComboBox(self.frame_15)
        self.w1.setGeometry(QtCore.QRect(28, 9, 126, 49))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.w1.setFont(font)
        self.w1.setObjectName("w1")
        self.gridLayout.addWidget(self.frame_15, 1, 3, 1, 1)
        self.frame_25 = QtWidgets.QFrame(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.frame_25.setFont(font)
        self.frame_25.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_25.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_25.setObjectName("frame_25")
        self.th3 = QtWidgets.QComboBox(self.frame_25)
        self.th3.setGeometry(QtCore.QRect(28, 9, 126, 49))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.th3.setFont(font)
        self.th3.setObjectName("th3")
        self.gridLayout.addWidget(self.frame_25, 3, 4, 1, 1)
        self.frame_8 = QtWidgets.QFrame(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.frame_8.setFont(font)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.tu1 = QtWidgets.QComboBox(self.frame_8)
        self.tu1.setGeometry(QtCore.QRect(28, 9, 126, 49))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.tu1.setFont(font)
        self.tu1.setObjectName("tu1")
        self.gridLayout.addWidget(self.frame_8, 1, 2, 1, 1)
        self.frame_5 = QtWidgets.QFrame(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.frame_5.setFont(font)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.m5 = QtWidgets.QComboBox(self.frame_5)
        self.m5.setGeometry(QtCore.QRect(28, 13, 126, 49))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.m5.setFont(font)
        self.m5.setObjectName("m5")
        self.gridLayout.addWidget(self.frame_5, 6, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 8, 0, 1, 1)
        self.frame_31 = QtWidgets.QFrame(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.frame_31.setFont(font)
        self.frame_31.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_31.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_31.setObjectName("frame_31")
        self.f42 = QtWidgets.QComboBox(self.frame_31)
        self.f42.setGeometry(QtCore.QRect(28, 26, 126, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.f42.setFont(font)
        self.f42.setObjectName("f42")
        self.f41 = QtWidgets.QComboBox(self.frame_31)
        self.f41.setGeometry(QtCore.QRect(28, 0, 126, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.f41.setFont(font)
        self.f41.setObjectName("f41")
        self.f43 = QtWidgets.QComboBox(self.frame_31)
        self.f43.setGeometry(QtCore.QRect(28, 50, 126, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.f43.setFont(font)
        self.f43.setObjectName("f43")
        self.gridLayout.addWidget(self.frame_31, 4, 5, 1, 1)
        self.frame_17 = QtWidgets.QFrame(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.frame_17.setFont(font)
        self.frame_17.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.w42 = QtWidgets.QComboBox(self.frame_17)
        self.w42.setGeometry(QtCore.QRect(28, 26, 126, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.w42.setFont(font)
        self.w42.setObjectName("w42")
        self.w41 = QtWidgets.QComboBox(self.frame_17)
        self.w41.setGeometry(QtCore.QRect(28, 0, 126, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.w41.setFont(font)
        self.w41.setObjectName("w41")
        self.w43 = QtWidgets.QComboBox(self.frame_17)
        self.w43.setGeometry(QtCore.QRect(28, 50, 126, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.w43.setFont(font)
        self.w43.setObjectName("w43")
        self.gridLayout.addWidget(self.frame_17, 4, 3, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 2, 0, 1, 1)
        self.frame_11 = QtWidgets.QFrame(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.frame_11.setFont(font)
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.tu3 = QtWidgets.QComboBox(self.frame_11)
        self.tu3.setGeometry(QtCore.QRect(28, 9, 126, 49))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.tu3.setFont(font)
        self.tu3.setObjectName("tu3")
        self.gridLayout.addWidget(self.frame_11, 3, 2, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 0, 5, 1, 1)
        self.frame_26 = QtWidgets.QFrame(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.frame_26.setFont(font)
        self.frame_26.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_26.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_26.setObjectName("frame_26")
        self.th5 = QtWidgets.QComboBox(self.frame_26)
        self.th5.setGeometry(QtCore.QRect(28, 13, 126, 49))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.th5.setFont(font)
        self.th5.setObjectName("th5")
        self.gridLayout.addWidget(self.frame_26, 6, 4, 1, 1)
        self.frame_16 = QtWidgets.QFrame(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.frame_16.setFont(font)
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.w2 = QtWidgets.QComboBox(self.frame_16)
        self.w2.setGeometry(QtCore.QRect(28, 9, 126, 49))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.w2.setFont(font)
        self.w2.setObjectName("w2")
        self.gridLayout.addWidget(self.frame_16, 2, 3, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 4, 0, 1, 1)
        self.frame_18 = QtWidgets.QFrame(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.frame_18.setFont(font)
        self.frame_18.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_18.setObjectName("frame_18")
        self.w3 = QtWidgets.QComboBox(self.frame_18)
        self.w3.setGeometry(QtCore.QRect(28, 9, 126, 49))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.w3.setFont(font)
        self.w3.setObjectName("w3")
        self.gridLayout.addWidget(self.frame_18, 3, 3, 1, 1)
        self.frame_14 = QtWidgets.QFrame(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.frame_14.setFont(font)
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.tu7 = QtWidgets.QComboBox(self.frame_14)
        self.tu7.setGeometry(QtCore.QRect(28, 8, 126, 49))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.tu7.setFont(font)
        self.tu7.setObjectName("tu7")
        self.gridLayout.addWidget(self.frame_14, 8, 2, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.frame_2.setFont(font)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.m2 = QtWidgets.QComboBox(self.frame_2)
        self.m2.setGeometry(QtCore.QRect(28, 9, 126, 49))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.m2.setFont(font)
        self.m2.setObjectName("m2")
        self.gridLayout.addWidget(self.frame_2, 2, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 7, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 6, 0, 1, 1)
        self.frame_22 = QtWidgets.QFrame(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.frame_22.setFont(font)
        self.frame_22.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_22.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_22.setObjectName("frame_22")
        self.th1 = QtWidgets.QComboBox(self.frame_22)
        self.th1.setGeometry(QtCore.QRect(28, 9, 126, 49))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.th1.setFont(font)
        self.th1.setObjectName("th1")
        self.gridLayout.addWidget(self.frame_22, 1, 4, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 0, 4, 1, 1)
        self.frame_34 = QtWidgets.QFrame(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.frame_34.setFont(font)
        self.frame_34.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_34.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_34.setObjectName("frame_34")
        self.f6 = QtWidgets.QComboBox(self.frame_34)
        self.f6.setGeometry(QtCore.QRect(28, 8, 126, 49))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.f6.setFont(font)
        self.f6.setObjectName("f6")
        self.gridLayout.addWidget(self.frame_34, 7, 5, 1, 1)
        self.frame_19 = QtWidgets.QFrame(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.frame_19.setFont(font)
        self.frame_19.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_19.setObjectName("frame_19")
        self.w5 = QtWidgets.QComboBox(self.frame_19)
        self.w5.setGeometry(QtCore.QRect(28, 13, 126, 49))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.w5.setFont(font)
        self.w5.setObjectName("w5")
        self.gridLayout.addWidget(self.frame_19, 6, 3, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 2, 1, 1)
        self.frame_13 = QtWidgets.QFrame(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.frame_13.setFont(font)
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.tu6 = QtWidgets.QComboBox(self.frame_13)
        self.tu6.setGeometry(QtCore.QRect(28, 8, 126, 49))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.tu6.setFont(font)
        self.tu6.setObjectName("tu6")
        self.gridLayout.addWidget(self.frame_13, 7, 2, 1, 1)
        self.frame_6 = QtWidgets.QFrame(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.frame_6.setFont(font)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.m6 = QtWidgets.QComboBox(self.frame_6)
        self.m6.setGeometry(QtCore.QRect(28, 8, 126, 49))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.m6.setFont(font)
        self.m6.setObjectName("m6")
        self.gridLayout.addWidget(self.frame_6, 7, 1, 1, 1)
        self.frame_29 = QtWidgets.QFrame(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.frame_29.setFont(font)
        self.frame_29.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_29.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_29.setObjectName("frame_29")
        self.f1 = QtWidgets.QComboBox(self.frame_29)
        self.f1.setGeometry(QtCore.QRect(28, 9, 126, 49))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.f1.setFont(font)
        self.f1.setObjectName("f1")
        self.gridLayout.addWidget(self.frame_29, 1, 5, 1, 1)
        self.frame_24 = QtWidgets.QFrame(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.frame_24.setFont(font)
        self.frame_24.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_24.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_24.setObjectName("frame_24")
        self.th42 = QtWidgets.QComboBox(self.frame_24)
        self.th42.setGeometry(QtCore.QRect(28, 26, 126, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.th42.setFont(font)
        self.th42.setObjectName("th42")
        self.th41 = QtWidgets.QComboBox(self.frame_24)
        self.th41.setGeometry(QtCore.QRect(28, 0, 126, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.th41.setFont(font)
        self.th41.setObjectName("th41")
        self.th43 = QtWidgets.QComboBox(self.frame_24)
        self.th43.setGeometry(QtCore.QRect(28, 50, 126, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.th43.setFont(font)
        self.th43.setObjectName("th43")
        self.gridLayout.addWidget(self.frame_24, 4, 4, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 3, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(470, 840, 311, 71))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setItalic(True)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.getData_and_update)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.create_database_connection()
        self.setup_combo_boxsex()

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)


    def create_database_connection(self):
        url = "https://ctbocdqgvhimayeqvqov.supabase.co"
        key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN0Ym9jZHFndmhpbWF5ZXF2cW92Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MDYzNjQ1MzEsImV4cCI6MjAyMTk0MDUzMX0.HHOqs4_KujahCS_V60CsKWjb0ky4UTO2qQNzdyV0sdU"
        self.supabase = create_client(url, key)


    def setup_combo_boxsex(self):
        resoponse = self.supabase.table('faculty_data').select("subject").execute()
        subject_list = []
        for subject in resoponse.data:
            subject_list.append(subject['subject'])
        subject_list.append("SHORT BREAK")
        subject_list.append("LUNCH BREAK")
        self.m1.addItems(subject_list)
        self.m2.addItems(subject_list)
        self.m3.addItems(subject_list)
        self.m41.addItems(subject_list)
        self.m42.addItems(subject_list)
        self.m43.addItems(subject_list)
        self.m5.addItems(subject_list)
        self.m6.addItems(subject_list)
        self.m7.addItems(subject_list)
        self.tu1.addItems(subject_list)
        self.tu2.addItems(subject_list)
        self.tu3.addItems(subject_list)
        self.tu41.addItems(subject_list)
        self.tu42.addItems(subject_list)
        self.tu43.addItems(subject_list)
        self.tu5.addItems(subject_list)
        self.tu6.addItems(subject_list)
        self.tu7.addItems(subject_list)
        self.w1.addItems(subject_list)
        self.w2.addItems(subject_list)
        self.w3.addItems(subject_list)
        self.w41.addItems(subject_list)
        self.w42.addItems(subject_list)
        self.w43.addItems(subject_list)
        self.w5.addItems(subject_list)
        self.w6.addItems(subject_list)
        self.w7.addItems(subject_list)
        self.th1.addItems(subject_list)
        self.th2.addItems(subject_list)
        self.th3.addItems(subject_list)
        self.th41.addItems(subject_list)
        self.th42.addItems(subject_list)
        self.th43.addItems(subject_list)
        self.th5.addItems(subject_list)
        self.th6.addItems(subject_list)
        self.th7.addItems(subject_list)
        self.f1.addItems(subject_list)
        self.f2.addItems(subject_list)
        self.f3.addItems(subject_list)
        self.f41.addItems(subject_list)
        self.f42.addItems(subject_list)
        self.f43.addItems(subject_list)
        self.f5.addItems(subject_list)
        self.f6.addItems(subject_list)
        self.f7.addItems(subject_list)

        self.set_Default_values()


    def set_Default_values(self):
        url = "https://ctbocdqgvhimayeqvqov.supabase.co"
        key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN0Ym9jZHFndmhpbWF5ZXF2cW92Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MDYzNjQ1MzEsImV4cCI6MjAyMTk0MDUzMX0.HHOqs4_KujahCS_V60CsKWjb0ky4UTO2qQNzdyV0sdU"
        supabase = create_client(url, key)
        response_1 = supabase.table("be_tt").select("*").eq("id", 1).execute()
        for data_1 in response_1.data:
            self.m1.setCurrentText(data_1["monday"])
            self.tu1.setCurrentText(data_1["tuesday"])
            self.w1.setCurrentText(data_1["wednesday"])
            self.th1.setCurrentText(data_1["thursday"])
            self.f1.setCurrentText(data_1["friday"])
        response_2 = supabase.table("be_tt").select("*").eq("id", 2).execute()
        for data_2 in response_2.data:
            self.m2.setCurrentText(data_2["monday"])
            self.tu2.setCurrentText(data_2["tuesday"])
            self.w2.setCurrentText(data_2["wednesday"])
            self.th3.setCurrentText(data_2["thursday"])
            self.f41.setCurrentText(data_2["friday"])
        response_3 = supabase.table("be_tt").select("*").eq("id", 3).execute()
        for data_3 in response_3.data:
            self.m3.setCurrentText(data_3["monday"])
            self.tu3.setCurrentText(data_3["tuesday"])
            self.w3.setCurrentText(data_3["wednesday"])
            self.th3.setCurrentText(data_3["thursday"])
            self.f3.setCurrentText(data_3["friday"])
        response_4 = supabase.table("be_tt").select("*").eq("id", 4).execute()
        for data_4 in response_4.data:
            self.m41.setCurrentText(data_4["monday"])
            self.tu41.setCurrentText(data_4["tuesday"])
            self.w41.setCurrentText(data_4["wednesday"])
            self.th41.setCurrentText(data_4["thursday"])
            self.f41.setCurrentText(data_4["friday"])
        response_5 = supabase.table("be_tt").select("*").eq("id", 5).execute()
        for data_5 in response_5.data:
            self.m42.setCurrentText(data_5["monday"])
            self.tu42.setCurrentText(data_5["tuesday"])
            self.w42.setCurrentText(data_5["wednesday"])
            self.th42.setCurrentText(data_5["thursday"])
            self.f42.setCurrentText(data_5["friday"])
        response_6 = supabase.table("be_tt").select("*").eq("id", 6).execute()
        for data_6 in response_6.data:
            self.m43.setCurrentText(data_6["monday"])
            self.tu43.setCurrentText(data_6["tuesday"])
            self.w43.setCurrentText(data_6["wednesday"])
            self.th43.setCurrentText(data_6["thursday"])
            self.f43.setCurrentText(data_6["friday"])
        response_7 = supabase.table("be_tt").select("*").eq("id", 7).execute()
        for data_7 in response_7.data:
            self.m5.setCurrentText(data_7["monday"])
            self.tu5.setCurrentText(data_7["tuesday"])
            self.w5.setCurrentText(data_7["wednesday"])
            self.th5.setCurrentText(data_7["thursday"])
            self.f5.setCurrentText(data_7["friday"])
        response_8 = supabase.table("be_tt").select("*").eq("id", 8).execute()
        for data_8 in response_8.data:
            self.m6.setCurrentText(data_8["monday"])
            self.tu6.setCurrentText(data_8["tuesday"])
            self.w6.setCurrentText(data_8["wednesday"])
            self.th6.setCurrentText(data_8["thursday"])
            self.f7.setCurrentText(data_8["friday"])
        response_9 = supabase.table("be_tt").select("*").eq("id", 9).execute()
        for data_9 in response_9.data:
            self.m7.setCurrentText(data_9["monday"])
            self.tu7.setCurrentText(data_9["tuesday"])
            self.w7.setCurrentText(data_9["wednesday"])
            self.th7.setCurrentText(data_9["thursday"])
            self.f7.setCurrentText(data_9["friday"])


    def getData_and_update(self):
        m1 = self.m1.currentText()
        m2 = self.m2.currentText()
        m3 = self.m3.currentText()
        m41 = self.m41.currentText()
        m42 = self.m42.currentText()
        m43 = self.m43.currentText()
        m5 = self.m5.currentText()
        m6 = self.m6.currentText()
        m7 = self.m7.currentText()
        tu1 = self.tu1.currentText()
        tu2 = self.tu2.currentText()
        tu3 = self.tu3.currentText()
        tu41 = self.tu41.currentText()
        tu42 = self.tu42.currentText()
        tu43 = self.tu43.currentText()
        tu5 = self.tu5.currentText()
        tu6 = self.tu6.currentText()
        tu7 = self.tu7.currentText()
        w1 = self.w1.currentText()
        w2 = self.w2.currentText()
        w3 = self.w3.currentText()
        w41 = self.w41.currentText()
        w42 = self.w42.currentText()
        w43 = self.w43.currentText()
        w5 = self.w5.currentText()
        w6 = self.w6.currentText()
        w7 = self.w7.currentText()
        th1 = self.th1.currentText()
        th2 = self.th2.currentText()
        th3 = self.th3.currentText()
        th41 = self.th41.currentText()
        th42 = self.th42.currentText()
        th43 = self.th43.currentText()
        th5 = self.th5.currentText()
        th6 = self.th6.currentText()
        th7 = self.th7.currentText()
        f1 = self.f1.currentText()
        f2 = self.f2.currentText()
        f3 = self.f3.currentText()
        f41 = self.f41.currentText()
        f42 = self.f42.currentText()
        f43 = self.f43.currentText()
        f5 = self.f5.currentText()
        f6 = self.f6.currentText()
        f7 = self.f7.currentText()

        self.supabase.table('be_tt').update({'monday' : m1, 'tuesday' : tu1, 'wednesday' : w1, 'thursday' : th1, 'friday' : f1}).eq('id', 1).execute()
        self.supabase.table('be_tt').update({'monday' : m2, 'tuesday' : tu2, 'wednesday' : w2, 'thursday' : th2, 'friday' : f2}).eq('id', 2).execute()
        self.supabase.table('be_tt').update({'monday' : m3, 'tuesday' : tu3, 'wednesday' : w3, 'thursday' : th3, 'friday' : f3}).eq('id', 3).execute()
        self.supabase.table('be_tt').update({'monday' : m41, 'tuesday' : tu41, 'wednesday' : w41, 'thursday' : th41, 'friday' : f41}).eq('id', 4).execute()
        self.supabase.table('be_tt').update({'monday' : m42, 'tuesday' : tu42, 'wednesday' : w42, 'thursday' : th42, 'friday' : f42}).eq('id', 5).execute()
        self.supabase.table('be_tt').update({'monday' : m43, 'tuesday' : tu43, 'wednesday' : w43, 'thursday' : th43, 'friday' : f43}).eq('id', 6).execute()
        self.supabase.table('be_tt').update({'monday' : m5, 'tuesday' : tu5, 'wednesday' : w5, 'thursday' : th5, 'friday' : f5}).eq('id', 7).execute()
        self.supabase.table('be_tt').update({'monday' : m6, 'tuesday' : tu6, 'wednesday' : w6, 'thursday' : th6, 'friday' : f6}).eq('id', 8).execute()
        self.supabase.table('be_tt').update({'monday' : m7, 'tuesday' : tu7, 'wednesday' : w7, 'thursday' : th7, 'friday' : f7}).eq('id', 9).execute()


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "BE Timetable Generator"))
        self.label_2.setText(_translate("MainWindow", "Time / Day"))
        self.label_5.setText(_translate("MainWindow", "Wednesday"))
        self.label_9.setText(_translate("MainWindow", "09:15 AM - 10:15 AM"))
        self.label_15.setText(_translate("MainWindow", "03:15 PM - 04:15 PM"))
        self.label_3.setText(_translate("MainWindow", "Monday"))
        self.label_10.setText(_translate("MainWindow", "10:15 PM - 11:15 AM"))
        self.label_7.setText(_translate("MainWindow", "Friday"))
        self.label_11.setText(_translate("MainWindow", "11:30 AM - 01:30 PM"))
        self.label_14.setText(_translate("MainWindow", "01:30 PM - 02:15 PM"))
        self.label_13.setText(_translate("MainWindow", "01:30 PM - 02:15 PM"))
        self.label_6.setText(_translate("MainWindow", "Thursday"))
        self.label_4.setText(_translate("MainWindow", "Tuesday"))
        self.label_12.setText(_translate("MainWindow", "11:15 AM - 11:30 AM"))
        self.pushButton.setText(_translate("MainWindow", "Update TimeTable"))


# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     MainWindow = QtWidgets.QMainWindow()
#     ui = Ui_timetable_generator()
#     ui.setupUi(MainWindow)
#     MainWindow.show()
#     sys.exit(app.exec_())
